qa: fix random failure due to unchanged mtime on directory operation
Most common failure was:

======================================================================
FAIL: test2 (__main__.Test.test2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test", line 374, in test2
    self.assertListEqual([b'a', b'a/c'], list(self.fssync.check(b'')))
AssertionError: Lists differ: [b'a', b'a/c'] != [b'a/c']