Warn instead of abort on a missing destination path when trying to backup it
This fixes the following error:
  [...]
  File "fssync", line 462, in sync
    self.backup(path)
  File "fssync", line 322, in backup
    self.rpc.wait()
  File "fssync", line 183, in wait
    raise r
FileNotFoundError: [Errno 2] No such file or directory: '...'

Such error should not happen if the only process modifying the destination is
fssync, but sometimes the easiest way to fix an issue like a permission error
is to delete paths on destination side.